// PLACES ACTIONS
export const ADD_PLACE = "ADD_PLACE";
export const DELETE_PLACE = "DELETE_PLACE";
export const SELECT_PLACE = "SELECT_PLACE";
export const DESELECT_PLACE = "DESELECT_PLACE";

// UI LOADER
export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";